In [61]:
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

  
# load the data
data = pd.read_csv('C:\\Users\\Admin\\Downloads\\dataset9000.csv')
dataset = pd.read_csv('C:\\Users\\Admin\\Downloads\\dataset9000.data', header = None)

In [63]:
data.head()

Database Fundamentals Computer Architecture Distributed Computing Systems  \
0          Professional        Not Interested                Not Interested   
1          Professional                  Poor                Not Interested   
2          Professional              Beginner                Not Interested   
3          Professional               Average                Not Interested   
4          Professional          Intermediate                Not Interested   

   Cyber Security      Networking Software Development Programming Skills  \
0  Not Interested  Not Interested       Not Interested     Not Interested   
1  Not Interested  Not Interested       Not Interested     Not Interested   
2  Not Interested  Not Interested       Not Interested     Not Interested   
3  Not Interested  Not Interested       Not Interested     Not Interested   
4  Not Interested  Not Interested       Not Interested     Not Interested   

  Project Management Computer Forensics Fundamentals Technical Communication  \
0     Not Interested                  Not Interested          Not Interested   
1     Not Interested                  Not Interested          Not Interested   
2     Not Interested                  Not Interested          Not Interested   
3     Not Interested                  Not Interested          Not Interested   
4     Not Interested                  Not Interested          Not Interested   

            AI ML Software Engineering Business Analysis Communication skills  \
0  Not Interested       Not Interested    Not Interested       Not Interested   
1  Not Interested       Not Interested    Not Interested       Not Interested   
2  Not Interested       Not Interested    Not Interested       Not Interested   
3  Not Interested       Not Interested    Not Interested       Not Interested   
4  Not Interested       Not Interested    Not Interested       Not Interested   

     Data Science Troubleshooting skills Graphics Designing  \
0  Not Interested         Not Interested     Not Interested   
1  Not Interested         Not Interested     Not Interested   
2  Not Interested         Not Interested     Not Interested   
3  Not Interested         Not Interested     Not Interested   
4  Not Interested         Not Interested     Not Interested   

                     Role  
0  Database Administrator  
1  Database Administrator  
2  Database Administrator  
3  Database Administrator  
4  Database Administrator

In [92]:
dataset.head()

Database Fundamentals  Computer Architecture  \
0                      9                      1   
1                      9                      2   
2                      9                      3   
3                      9                      5   
4                      9                      6   

   Distributed Computing Systems  Cyber-Security  Networking  Development  \
0                              1               1           1            1   
1                              1               1           1            1   
2                              1               1           1            1   
3                              1               1           1            1   
4                              1               1           1            1   

   Programming Skills  Project Management  Computer Forensics Fundamentals  \
0                   1                   1                                1   
1                   1                   1                                1   
2                   1                   1                                1   
3                   1                   1                                1   
4                   1                   1                                1   

   Technical Communication  AI ML  Software Engineering  Business Analysis  \
0                        1      1                     1                  1   
1                        1      1                     1                  1   
2                        1      1                     1                  1   
3                        1      1                     1                  1   
4                        1      1                     1                  1   

   Communication skills  Data Science  Troubleshooting-skills  \
0                     1             1                       1   
1                     1             1                       1   
2                     1             1                       1   
3                     1             1                       1   
4                     1             1                       1   

   Graphics Designing                   Roles  
0                   1  Database Administrator  
1                   1  Database Administrator  
2                   1  Database Administrator  
3                   1  Database Administrator  
4                   1  Database Administrator

In [65]:
X=np.array(dataset.iloc[:, 0:17]) 
print(X)
Y = np.array(dataset.iloc[:, 17])
print(Y)
dataset.columns= ["Database Fundamentals","Computer Architecture","Distributed Computing Systems",
"Cyber-Security","Networking","Development","Programming Skills","Project Management",
"Computer Forensics Fundamentals","Technical Communication","AI ML","Software Engineering","Business Analysis",
"Communication skills","Data Science","Troubleshooting-skills","Graphics Designing","Roles"]
dataset.dropna(how ='all', inplace = True)

[[9 1 1 ... 1 1 1]
 [9 2 1 ... 1 1 1]
 [9 3 1 ... 1 1 1]
 ...
 [1 1 1 ... 6 6 9]
 [1 1 1 ... 7 7 9]
 [1 1 1 ... 7 5 9]]
['Database Administrator' 'Database Administrator'
 'Database Administrator' ... 'Graphics Designer' 'Graphics Designer'
 'Graphics Designer']


In [67]:
# Building the DecisionTreeClassifier Model
# Set the seed for reproducibility
seed = 5
kfold = model_selection.KFold(n_splits=15)

# Initialize the base classifier
base_cls = DecisionTreeClassifier()

# Number of base classifiers
num_trees = 50

# Bagging classifier
model = BaggingClassifier(estimator=base_cls,
                          n_estimators=num_trees,
                          random_state=seed)

# Evaluate the model with cross-validation
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print("Accuracy:", results.mean() * 100)


Accuracy: 82.35294117647058


In [68]:
from sklearn.model_selection import train_test_split

# Split your data into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=seed)

# Fit the model to the training data
model.fit(X_train, Y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50,
                  random_state=5)

In [69]:
Y_test

array(['Information Security Specialist', 'Graphics Designer',
       'Cyber Security Specialist', ..., 'Database Administrator',
       'AI ML Specialist', 'AI ML Specialist'], dtype=object)

In [90]:
# Make predictions on new data (e.g., X_test or any new sample)
new_data = [[3, 3, 3, 9, 2, 2, 1, 1, 1, 1, 7, 3, 2, 1, 1, 2,5]]  # Replace this with your new input data, shaped as [n_samples, n_features]
predictions = model.predict(new_data)
# Output the predictions
print("Predictions for new data:", predictions)

Predictions for new data: ['Cyber Security Specialist']


In [88]:
dataset['Database Fundamentals'].unique()

array([9, 1, 2, 3, 5, 6, 7], dtype=int64)